query Characters($url: String!) {
  characterDetails(url: $url) {
    name
    height
    mass
    hair_color
    skin_color
    eye_color
    birth_year
    gender
    homeworld {
      name
    }
    films {
      title
      episode_id
    }
    vehicles {
      name
      created
    }
    starships {
      name
      created
    }
    created
    url
  }
}
