export const ActionTypes = {
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
  DELETE_FAVORITE_LIST: 'DELETE_FAVORITE_LIST',
  IS_DARK_THEME: 'IS_DARK_THEME',
  IS_LOADING: 'IS_LOADING',
  IS_DISPLAY: 'IS_DISPLAY',
  FETCH_DATA_FROM_API: 'FETCH_DATA_FROM_API',
  CHARACTERS_AMOUNT: 'CHARACTERS_AMOUNT',
  SEARCH_ERROR: 'SEARCH_ERROR',
  CHARACTER_DETAILS: 'CHARACTER_DETAILS',
  PAGE_NUMBER: 'PAGE_NUMBER',
} as const;
