export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
export const DELETE_FAVORITE_LIST = 'DELETE_FAVORITE_LIST';
export const SET_THEME = 'SET_THEME';
